version: 0.0
os: linux
files:
  - source: /  # Source directory in the GitHub repository
    destination: /opt/codedeploy-agent/deployment-root/6b279fec-32b6-4172-ab6c-5471e5f13219/  # Destination on the EC2 instance

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh  # Path to the script relative to your source
      timeout: 300
      runas: root  # Ensure the script runs as root

  AfterInstall:
    - location: scripts/after_install.sh   # Path to the script relative to your source
      timeout: 300
      runas: root  # Ensure the script runs as root

  ApplicationStart:
    - location: scripts/start_application.sh  # Path to the script relative to your source
      timeout: 300
      runas: root  # Ensure the script runs as root
