version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/next-ecommerce

hooks:
  # Stops the application if it's already running
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

  # Installs necessary dependencies after files are copied
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  # Starts the application
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  # Validates the service to confirm it's running as expected
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

