version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify your Node.js version
    commands:
      - echo Installing dependencies...
      - npm install

artifacts:
  files:
    - '**/*'  # Include all files in the output artifacts

